[workspace]
members = ["code-ingest"]
resolver = "2"

[workspace.dependencies]
# CLI argument parsing
clap = { version = "4.0", features = ["derive"] }

# Database operations
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "migrate"] }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Cryptographic hashing
sha2 = "0.10"

# File system traversal
walkdir = "2.3"

# MIME type detection
mime_guess = "2.0"
mime = "0.3"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Additional utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"

# Parallel processing
rayon = "1.8"

# Validation framework specific
sysinfo = "0.30"
serde_json = "1.0"
toml = "0.8"
num_cpus = "1.0"

# Content extraction dependencies
encoding_rs = "0.8"
scraper = "0.15"
html2md = "0.2"
zip = "0.5"
quick-xml = "0.28"
serde_yaml = "0.8"
pdf-extract = "0.6"

# Git operations
git2 = "0.18"

# Progress reporting
indicatif = "0.17"

# URL parsing
url = "2.4"

# Logging and tracing
tracing = "0.1"

# Gitignore pattern matching
ignore = "0.4"


