# Pensieve Validator Configuration File
# This file contains all configuration options for the pensieve validation framework

[validation]
# Enable real-time analysis during validation
enable_real_time_analysis = true

# Metrics collection interval in milliseconds
metrics_collection_interval_ms = 500

# Enable chaos detection (problematic files analysis)
enable_chaos_detection = true

# Enable deduplication analysis
enable_deduplication_analysis = true

# Enable user experience analysis
enable_ux_analysis = true

# Enable performance profiling
enable_performance_profiling = true

[pensieve]
# Path to pensieve binary (leave empty to use system PATH)
# binary_path = "/usr/local/bin/pensieve"

# Timeout in seconds for pensieve execution
# timeout_seconds = 3600

# Memory limit in MB for pensieve process
# memory_limit_mb = 8192

# Enable deduplication in pensieve
# enable_deduplication = true

# Enable verbose output from pensieve
# verbose_output = false

# Additional arguments to pass to pensieve
# additional_args = ["--some-flag", "--another-option"]

[monitoring]
# Enable CPU monitoring
# enable_cpu_monitoring = true

# Enable memory monitoring
# enable_memory_monitoring = true

# Enable I/O monitoring
# enable_io_monitoring = true

# Monitoring interval in milliseconds
# monitoring_interval_ms = 500

# Enable detailed process monitoring
# enable_detailed_monitoring = true

[performance]
# Minimum files per second threshold
# min_files_per_second = 1.0

# Maximum memory usage in MB
# max_memory_mb = 8192

# Maximum CPU usage percentage
# max_cpu_percent = 80.0

# Maximum error rate per minute
# max_error_rate_per_minute = 5.0

# Minimum UX score (0.0 - 10.0)
# min_ux_score = 7.0

[output]
# Output directory for reports (leave empty for current directory)
# output_directory = "./validation_reports"

# Enable JSON output
enable_json_output = true

# Enable HTML report generation
enable_html_reports = true

# Enable CSV export
enable_csv_export = false

# Include detailed metrics in output
include_detailed_metrics = true

# Include raw data in output
include_raw_data = false

[logging]
# Log level: error, warn, info, debug, trace
level = "info"

# Enable file logging
enable_file_logging = false

# Log file path (only used if file logging is enabled)
# log_file_path = "./pensieve-validator.log"

# Enable structured logging (JSON format)
enable_structured_logging = false

# Enable progress reporting
enable_progress_reporting = true

# Progress update interval in milliseconds
progress_update_interval_ms = 1000